### ISSUE TITLE
RSS feed not available, uploaded zip file

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/arthropodEasyCaptureAMNH#5]
The RSS feed for this collection is no longer available so I uploaded the zip file. It is static and will not change. @jhpoelen do you have suggestions on how to best make this information available?

**Comment by jhpoelen** [comment]
@seltmann thanks for having the foresight to capture the dwca related to the Tri-Trophic TCN. 

I'd imagine creating a repository for each dwca (digital bee, . . . ), enabling Zenodo integration, create a release,  and then let GloBI index it.

After that, we can mark the arthropodEasyCaptureAMNH as deprecated. 

What you think about this proposed publishing method?

**Comment by seltmann** [comment]
@jhpoelen sounds like a good plan. I will get this started.
